"""baseline_schema

Revision ID: f01ce7c7e110
Revises: 
Create Date: 2026-08-12 02:40:16.312751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01ce7c7e110'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_bookings_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('broker_profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_broker_profiles_user_id'), ['user_id'])

    with op.batch_alter_table('builders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_builders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_builders_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_commissions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_commissions_booking_id'), ['booking_id'])
        batch_op.create_foreign_key(batch_op.f('fk_commissions_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_followups_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_followups_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_leads_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_notifications_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_organization_settings_organization_id'), ['organization_id'])

    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_used', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_sent_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('otp_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('registration_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_payments_razorpay_payment_id')
        batch_op.create_index(batch_op.f('ix_payments_razorpay_payment_id'), ['razorpay_payment_id'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_payments_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_payments_plan_id_plans'), 'plans', ['plan_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_payments_registration_id_registration_requests'), 'registration_requests', ['registration_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_projects_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('sales_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_targets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sales_targets_organization_id_organizations'), 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_password_change', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('force_password_change')

    with op.batch_alter_table('sales_targets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_targets_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_targets_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_registration_id_registration_requests'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_payments_plan_id_plans'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_payments_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_razorpay_payment_id'))
        batch_op.create_index('ix_payments_razorpay_payment_id', ['razorpay_payment_id'], unique=False)
        batch_op.drop_column('plan_id')
        batch_op.drop_column('registration_id')
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.alter_column('otp_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('last_sent_at')
        batch_op.drop_column('is_used')
        batch_op.drop_column('otp_hash')

    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_organization_settings_organization_id'), type_='unique')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leads_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leads_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_followups_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_followups_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_commissions_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_commissions_booking_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_commissions_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('builders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_builders_organization_id_organizations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_builders_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('broker_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_broker_profiles_user_id'), type_='unique')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookings_organization_id_organizations'), type_='foreignkey')

    # ### end Alembic commands ###
